uint8 LEFT_PIPE=0
uint8 RIGHT_PIPE=1

uint8 pipe

uint8 INTAKE=0
uint8 L1=1
uint8 L2=2
uint8 L3=3
uint8 L4=4

uint8 level
---
bool success
---
uint8 ALIGNING=0
uint8 ALIGNING_PLACING=1
uint8 PLACING=2
uint8 PLACED=3

uint8 stage