teleop_params:
    num_joysticks: 2
    max_rot: 4.0
    max_rot_slow: 2.355
    rotation_axis_scale: 1.0
    rotation_epsilon: 0.002 # Z-velocities lower than this indicate robot is stopped  # WAS 0.2 if things look wrong!! 
    min_speed: 0.0  # Smallest linear speed which get the robot moving at all
    max_speed: 6.0
    max_speed_slow: 1.7
    joystick_pow: 1.5
    rotation_pow: 1.0   #Scaling factors used in teleop_joystick_comp
    joystick_deadzone: 0.05
    radial_deadzone: 0.05
    drive_rate_limit_time: 1
    rotate_rate_limit_time: 1
    trigger_threshold: 0.5
    stick_threshold: 0.5
    button_move_speed: 0.5
    imu_zero_angle: 0.0

orientation_profile:
    speed: 4.0
    acceleration: 12.0
    jerk: 72.0
    