elevator_controller:
    type: talonfxpro_controllers/TalonFXProVoltageOutputController
    joint: elevator_leader
    invert: clockwise_positive

    sensor_to_mechanism_ratio: 161.030098 # radians per meter
    dynamic_reconfigure: True
    neutral_mode: Brake

elevator_follower_controller:
    type: talonfxpro_controllers/TalonFXProFollowerController
    joint: elevator_follower
    follow_joint: elevator_leader
    control_oppose_master_direction: True

    sensor_to_mechanism_ratio: 161.030098 # radians per meter
    neutral_mode: Brake
    dynamic_reconfigure: True