bl_cancoder_controller:
    type:       cancoder_controller/CANCoderController
    joint_name: bl_cancoder
    magnet_offset: 1.21491
    dynamic_reconfigure: False
    enable_read_thread: False

br_cancoder_controller:
    type:       cancoder_controller/CANCoderController
    joint_name: br_cancoder
    magnet_offset: 0.454058
    dynamic_reconfigure: False
    enable_read_thread: False

fl_cancoder_controller:
    type:       cancoder_controller/CANCoderController
    joint_name: fl_cancoder
    magnet_offset: 1.72113
    dynamic_reconfigure: False
    enable_read_thread: False

fr_cancoder_controller:
    type:       cancoder_controller/CANCoderController
    joint_name: fr_cancoder
    magnet_offset: 0.720971
    dynamic_reconfigure: False
    enable_read_thread: False

