# ff for first stage (0.0 - 0.615) = 0.3 V
# second stage (0.615 - 1.245) = 0.35 V
# third stage (1.245 - 1.875) = 0.35 V
# hard stop: 1.825 m
# Zeroing threshold: 24A

elevator_controller:
    type: talonfxpro_controllers/TalonFXProVoltageOutputController
    joint: elevator_leader
    invert: clockwise_positive

    sensor_to_mechanism_ratio: 161.030098 # radians per meter
    dynamic_reconfigure: True
    neutral_mode: Brake

elevator_follower_controller:
    type: talonfxpro_controllers/TalonFXProFollowerController
    joint: elevator_follower
    follow_joint: elevator_leader
    control_oppose_master_direction: True

    sensor_to_mechanism_ratio: 161.030098 # radians per meter
    neutral_mode: Brake
    dynamic_reconfigure: True