bl_cancoder_controller:
    type:       cancoder_controller/CANCoderController
    joint_name: bl_cancoder
    magnet_offset: 1.21184
    dynamic_reconfigure: False
    enable_read_thread: False

br_cancoder_controller:
    type:       cancoder_controller/CANCoderController
    joint_name: br_cancoder
    magnet_offset: 0.585981
    dynamic_reconfigure: False
    enable_read_thread: False

fl_cancoder_controller:
    type:       cancoder_controller/CANCoderController
    joint_name: fl_cancoder
    magnet_offset: 1.73033
    dynamic_reconfigure: False
    enable_read_thread: False

fr_cancoder_controller:
    type:       cancoder_controller/CANCoderController
    joint_name: fr_cancoder
    magnet_offset: 0.711767
    dynamic_reconfigure: False
    enable_read_thread: False