# height in meters
intake: 0.0
L1: 0.2
L2: 0.4
L3: 0.6
L4: 1.77

avoid_elevator_switch: elevator_avoid_limit_switch
outtake_switch: roller_limit_switch

tolerance: 0.03 # m

controller_name: elevator_controller
joint_name: elevator_leader