legal_tags: 
    # - 1
    # - 2
    # - 3
    # - 4
    # - 5
    - 6 # start of red reef
    - 7
    - 8
    - 9
    - 10
    - 11 # end of red reef
    # - 12
    # - 13
    # - 14
    # - 15
    # - 16
    - 17 # start of blue reef
    - 18
    - 19
    - 20
    - 21
    - 22 # end of blue reef

# Default is 5, which tends to detect a lot of false positives in the
# first stage of detection.  Increasing this value will reduce the number
# of false positives, but may also reduce detection rate a bit.
# Since we already run at 60FPS x2 cameras we can afford to
# leave it at the default for now.
min_white_black_diff: 5
