nav_msgs/Path position_path
nav_msgs/Path position_waypoints
nav_msgs/Path velocity_path
nav_msgs/Path velocity_waypoints
int32[] waypointsIdx # waypoints are largely irrelvent with paths being split up by choreo

# Linear and angular tolerances for finishing path
# Set to non-zero to override config defaults
float64 final_pos_tol
float64 final_vel_tol
float64 final_rot_tol
float64 final_angvel_tol

bool dont_go_to_start
bool wait_at_last_endpoint # if true, will wait (and keep correcting error) at last endpoint until timeout
bool enforce_actually_localized # if true, will wait for difference between frc_robot (tagslam frame) and base_link to be less than some param-configurable value
---
bool timed_out
bool success
---
float32 percent_complete
float32 percent_next_waypoint
int32 current_waypoint
# progress towards current target
float64 x_error
float64 y_error
float64 angle_error
float64 baselink_vs_tagslam_difference